server:
    shutdown: graceful #immediate
    port: 14382
    servlet:
        context-path: /developer
spring:
    application:
        name: dataUpload
    resources:
        static-locations: classpath:/static,classpath:/public  #文件路径
    lifecycle:
        timeout-per-shutdown-phase: 1s #优雅关闭项目的时间，默认时30
    mvc:
        static-path-pattern: static/**   #映射路径
    liquibase:
        change-log: classpath:changelog/changelog-master.xml
        test-rollback-on-update: true
        enabled: true
    datasource:
        # 数据源基本配置
        dbType: sqlserver
        username: sa
        password: Lajimima_123
        url: jdbc:sqlserver://localhost;DatabaseName=huaian
        type: com.alibaba.druid.pool.DruidDataSource
    main:
        allow-bean-definition-overriding: true

##mybatis-plus配置文件
mybatis-plus:
    mapper-locations: classpath*:mybatis/*.xml
    #实体扫描，多个package用逗号或者分号分隔
    typeAliasesPackage: com.supcon.ses.report.model.entity
    type-aliases-package: com.supcon.ses.report.model.entity
    check-config-location: true
    configuration:
        #是否开启自动驼峰命名规则（camel case）映射
        map-underscore-to-camel-case: true
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 关闭日志
        #log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
        cache-enabled: false
        call-setters-on-nulls: true
        #配置JdbcTypeForNull, oracle数据库必须配置
        jdbc-type-for-null: null
        #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
        auto-mapping-unknown-column-behavior: warning


## PageHelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

async-pool:
    test:
        corePoolSize: 2
        maxPoolSize: 4
        keepAliveSeconds: 120
        queueCapacity: 10
